core/login/urls.py
from unicodedata import name
from django.urls import path
from .views import *

app_name = 'login'


urlpatterns = [
    path('login/',LoginFormView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('',DashboardView.as_view(),name='dashboard')
]

core/nurse/urls.py
from django.urls import path
from .views import *

app_name = 'nurse'

urlpatterns = [
    path('list/',NurseListView.as_view(),name='nurse_list'),
    path('create/',NurseCreateView.as_view(),name='nurse_create'),
    path('update/<int:pk>/',NurseUpdateView.as_view(),name='nurse_update'),
    path('delete/<int:pk>/',NurseDeleteView.as_view(),name='nurse_delete'),
]

core/sale/urls.py
from django.urls import path
from .views import *

app_name = 'sale'

urlpatterns = [ 

    #Sale
    path('add/',SaleCreateView.as_view(),name="sale_create"),
    path('list/',SaleListView.as_view(), name='sale_list'),
    path('delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('update/<int:pk>/', SaleUpdateView.as_view(), name='sale_update'),
    path('invoice/pdf/<int:pk>/', SaleInvoicePdfView.as_view(), name='sale_invoice_pdf'),
    path('total/',TotalSaleListView.as_view(),name='sale_total'),
    path('by-doctor/',SaleByDoctorListView.as_view(),name='sales_by_doctor')
]

core/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('list/',UserListView.as_view(),name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.login.urls')),
    path('user/',include('core.user.urls')),
    path('doctor/',include('core.doctor.urls')),
    path('nurse/',include('core.nurse.urls')),
    path('patient/',include('core.patient.urls')),
    path('appointment/',include('core.appointment.urls')),
    path('product/',include('core.product.urls')),
    path('sale/',include('core.sale.urls')),
    path('office/',include('core.office.urls')),
    path('clinical-history/',include('core.clinical_history.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="">Home</a></li>
                                <!--<li class="breadcrumb-item"><a href=""></a></li> -->
                                <li class="breadcrumb-item"><a href="">{{request.user.municipio.mcpio}}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'login:dashboard' %}" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href=""
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login:logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-dark elevation-4">
    <a href="{% url 'login:dashboard' %}" class="brand-link">
        <img src="{% static 'img/logo.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Hospital DBST</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimiento</li>
                <li class="nav-item">
                    <a href="" class="nav-link">
                        
                        <i class="fa fa-file" aria-hidden="true"></i>
                        <p>
                               Pagina Principal
                        </p>
                        
                    </a>
                </li>
                    {% if perms.user.view_user %}
                        <li class="nav-item">
                            <a href="{% url 'user:user_list' %}" class="nav-link"> 
                                <i class="fa fa-users" aria-hidden="true"></i>
                                <p>
                                    USUARIOS
                                </p>
                            </a>
                        </li>
                    {% endif %} 
                    
                    {% if perms.office.view_office %}
                        <li class="nav-item">
                            <a href="{% url 'office:office_list' %}" class="nav-link">
                                <i class="fa fa-home" aria-hidden="true"></i>
                                <p>
                                    CONSULTORIOS
                                </p>
                            </a>
                        </li>
                    {% endif %} 

                    {% if perms.doctor.view_doctor %}
                        <li class="nav-item">
                            <a href="{% url 'doctor:doctor_list' %}" class="nav-link">
                                <i class="fa fa-user-md" aria-hidden="true"></i>
                                <p>
                                    DOCTORES
                                </p>
                            </a>
                        </li>
                    {% endif %}

                    {% if perms.appointment.view_appointment %}
                        <li class="nav-item">
                            <a href="{% url 'appointment:appointment_by_doctor_list' %}" class="nav-link">
                                <i class="fa fa-user-md" aria-hidden="true"></i>
                                <p>
                                    CITAS POR DOCTOR
                                </p>
                            </a>
                        </li>
                    {% endif %}
                

                {% if perms.nurse.view_nurse %}
                    <li class="nav-item">
                        <a href="{% url 'nurse:nurse_list' %}" class="nav-link"> 
                            <i class="fa fa-medkit" aria-hidden="true"></i>
                            <p>
                                ENFERMEROS
                            </p>
                        </a>
                    </li> 
                {% endif %}


                {% if perms.patient.view_patient %}
                    <li class="nav-item">
                        <a href="{% url 'patient:patient_list' %}" class="nav-link"> 
                            <i class="fa fa-users" aria-hidden="true"></i>
                            <p>
                                PACIENTES
                            </p>
                        </a>
                    </li>
                {% endif %}

                {% if perms.clinical_history.view_clinicalhistory %}
                    <li class="nav-item">
                        <a href="{% url 'clinical_history:clinical_history_list' %}" class="nav-link"> 
                            <i class="fa fa-th" aria-hidden="true"></i>
                            <p>
                                HISTORIAL CLINICO
                            </p>
                        </a>
                    </li> 
                {% endif %}
                
                {% if perms.appointment.view_appointment %}
                <li class="nav-item">
                    <a href="{% url 'appointment:appointment_list' %}" class="nav-link"> 
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                        <p>
                            CITAS
                        </p>
                    </a>
                </li>
                {% endif %}

                {% if perms.appointment.view_appointment %}
                    <li class="nav-item">
                        <a href="{% url 'appointment:appointment_by_patient_list' %}" class="nav-link"> 
                            <i class="fa fa-history" aria-hidden="true"></i>
                            <p>
                                HISTORIAL DE CITAS POR PACIENTE
                            </p>
                        </a>
                    </li>
                {% endif %}

                {% if perms.sale.view_sale %}
                    <li class="nav-item">
                        <a href="{% url 'sale:sale_list' %}" class="nav-link"> 
                            <i class="fa fa-heartbeat" aria-hidden="true"></i>
                            <p>
                                RECETAS
                            </p>
                        </a>
                    </li>
                {% endif %}

                {% if perms.sale.view_sale %}
                    <li class="nav-item">
                        <a href="{% url 'sale:sales_by_doctor' %}" class="nav-link"> 
                            <i class="fa fa-book" aria-hidden="true"></i>
                            <p>
                                RECETAS POR MEDICO
                            </p>
                        </a>
                    </li>
                {% endif %}

                {% if perms.product.view_category %}
                    <li class="nav-item">
                        <a href="{% url 'product:category_list' %}" class="nav-link"> 
                            <i class="fa fa-cubes" aria-hidden="true"></i>
                            <p>
                                CATEGORIAS
                            </p>
                        </a>
                    </li>
                {% endif %}

                {% if perms.product.view_product%}
                    <li class="nav-item">
                        <a href="{% url 'product:product_list' %}" class="nav-link"> 
                            <i class="fa fa-archive" aria-hidden="true"></i>
                            <p>
                                PRODUCTOS
                            </p>
                        </a>
                    </li> 
                {% endif %}

                {% if perms.user.view_user %}    
                <li class="nav-item">
                    <a href="{% url 'sale:sale_total' %}" class="nav-link"> 
                        <i class="fa fa-male" aria-hidden="true"></i>
                        <p>
                            VENTAS TOTALES POR CLIENTE
                        </p>
                    </a>
                </li> 
                {% endif %}
        
            </ul>
        </nav>
    </div>
</aside>